### ISSUE TITLE
PDA Mouse activity is inconsistent

### ISSUE THREAD

**Issue by yohjimane** [yohjimane/xray-16#17]
**Describe the bug**
Sometimes when activating the PDA, the mouse doesn't activate when expected to.

**To Reproduce**
Not sure yet

**Expected behavior**
Mouse should behave reliably (only active while PDA is zoomed)

**Comment by tiltedcan** [comment]
this might not be just tied to the pda as the mouse sometimes refuses to appear for me in dialogue/inventory/trading window. Haven't been able to consistently replicate it yet but will update if I do. sidenote, I am always able to get the mouse to come back by clearing whatever window I am in and going into my inventory and then back out

**Comment by tiltedcan** [comment]
I have finally been able to successfully repro this.

**Describe the bug**
Mouse cursor disappears in various ui windows including dialog windows, loot container windows, and pda 

**To Reproduce**
Steps to reproduce the behavior:
1. go to Yanov
2. alt-tab to another window
3. alt-tab back into OXRGS 
4. open PDA then close it
5. talk to Hawaiian and mouse cursor will be invisible

**Expected behavior**
Mouse cursor will be visible when opening a UI window

**BugTrap error report**
[openxray.log](https://github.com/yohjimane/xray-16/files/14862512/openxray.log)


**Desktop (please complete the following information):**
 - OS: Windows 11 (AtlasOS)
 - OpenXRay Gunslinger v0.0.1 with hotfix v0.1.0

**Additional context**
I regex scrubbed the thousands of duplicate lines from the log to make it easier to read, if I should avoid doing this in future please let me know.

**Comment by yohjimane** [comment]
This one should be fixed with hotfix v0.1.01 - please give it a try and let me know how it goes :)

**Comment by tiltedcan** [comment]
Haven't been able to get this to happen after the update I think it can safely be marked as solved
