### ISSUE TITLE
Can't activate or deactivate headlamp without weapon equiped

### ISSUE THREAD

**Issue by RenegadoHS** [yohjimane/xray-16#19]
If you don't have a weapon equiped you can't press L and toggle your  flashlight

**Comment by tiltedcan** [comment]
I am having this issue as well, will investigate further to provide more useful info

**Comment by tiltedcan** [comment]
Updating with full bug write up to follow template.

**Describe the bug**
Headlamp keybind will not work correctly unless player character has weapon drawn

**To Reproduce**
Steps to reproduce the behavior (7/7 times 100% reproduction rate):
1. Boot into the game and load any save or start a new game
2. Press key that you have bound for headlamp
3. If you have a weapon drawn, headlamp toggle animation will play and headlamp will be toggled
4. If you have no weapon drawn, headlamp toggle animation will not play and headlamp will not be toggled

**Expected behavior**
Regardless of whether or not the player character has a weapon drawn headlamp toggle animation will play and headlamp will be toggled

**BugTrap error report**
N/A

**Desktop**
 - OS: Windows 11 (Atlas OS)
 - OpenXRay Gunslinger v0.0.1 with hotfix v0.1.01

**Comment by tiltedcan** [comment]
This issue isn't reproducible on current hotfix 12, safe to close for now.
