### ISSUE TITLE
Flickering in certain scopes

### ISSUE THREAD

**Issue by tiltedcan** [yohjimane/xray-16#27]
**Describe the bug**
Certain scopes in the game will have a flickering effect during ads

**To Reproduce**
1. Equip one of the affected scopes on one of the affected weapons
2. Aim down sights with said affected weapon/scope
3. See error - flickering effect

**Expected behavior**
view model of weapon and scope will remain solid

**Screenshots**
will update with footage of issue

**BugTrap error report**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 (Atlas OS)
 - OpenXRay Gunslinger  v0.0.1 with hotfix  v0.0.9

**Additional context**
Thus far the scope/weapon combinations I have found are the ASVAL with the PSO1m2 and the RPG7 with the scope attachment, I will add to this if I find more.

**Comment by tiltedcan** [comment]
https://github.com/yohjimane/xray-16/assets/12876132/102bd9ca-3c93-4401-839c-0cf677cbe0f8

**Comment by tiltedcan** [comment]
this behavior appears to apply to any weapon that I can mount the PSO-1M2 Scope onto

**Comment by yohjimane** [comment]
This bug really really sucks because it's the same logic for all these scopes - but it only seems to affect some of them. I'm looking into it, but this one is actually a bit more complex than it seems.

**Comment by tiltedcan** [comment]
1PN93-1 Assault night sight also demonstrates this behavior (tested with AKS-74U and AK-74M)

**Comment by tiltedcan** [comment]
PN-23 Assault night sight also demonstrates this behavior (tested with Wincheaster 1300 and HK MP5)

**Comment by yohjimane** [comment]
Make sure to note what scope / weapon combos could cause it, it would be more concerning if same scope works on some weapons, but not on others

**Comment by tiltedcan** [comment]
updated my comments to include that info

**Comment by yohjimane** [comment]
Its also worth noting: This bug only occurs with old-school style of second view port (SVP) render. It's because we need to hide the scope before re-rendering the scene so that the image doesn't become recursive (see image)
![image](https://github.com/yohjimane/xray-16/assets/11345783/b032a3df-9967-4966-b0d2-04dac9f9b538)


With the new implementation i showed off in a devlog a while back, where the position of the camera used to render the SVP is set to position of the scope, we can avoid this issue by:
- adding config camera offsets per scope/weapon combination
- not hiding the scope, in favor of pushing the camera slightly forward instead with the offset configs

I didn't enable this feature yet, because i'm too lazy to configure each scope on my own, but if you want to play around with it / update configs- let me know

**Comment by tiltedcan** [comment]
This should be fixed with hotfix v0.1.07
